# Generated by Django 5.1.5 on 2025-01-27 16:24

from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0001_initial'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.AlterField(
            model_name='wallet',
            name='members',
            field=models.ManyToManyField(related_name='core_wallets', to=settings.AUTH_USER_MODEL),
        ),
    ]
